name: rebuild release

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: alchemicalartist
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: "./src"
          file: ./src/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: alchemicalartist/nix-devcontainer:${{ steps.vars.outputs.tag }}